server:
  port: 8003
spring:
  data:
      elasticsearch:
        cluster-name: elasticsearch 
        cluster-nodes: 127.0.0.1:9300
  application:
    name: daydayshoping-common
eureka:
  client:
     service-url:
      defaultZone: http://localhost:7001/eureka #注册中心地址