server:
  port: 9001
spring:
  application:
    name: USER-CONSUMER
eureka:
  client:
    registerWithEureka: false #不注册到Eureka,不在注册中心显示
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka #注册中心地址