server:
  port: 8002
spring:
  application:
    name: PRODUCT-MANAGER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daydayshoping_product
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:org/dengyu/daydayshoping/mapper/*Mapper.xml
  type-aliases-package: org.dengyu.daydayshoping.domain,org.dengyu.daydayshoping.query
eureka:
  client:
     service-url:
      defaultZone: http://localhost:7001/eureka #注册中心地址